// Small Web Crypto helpers (available in workerd, browsers and Node 24). Native HMAC/SHA/AES keep the
// server's CPU per request low (docs/05 §1.2: target p99 ≤ 7 ms on the Free plan).
import { constantTimeEqual } from "@oslojs/crypto/subtle";
import {
  decodeBase64urlIgnorePadding,
  encodeBase32NoPadding,
  encodeBase64urlNoPadding,
  encodeHexLowerCase,
} from "@oslojs/encoding";

export const enc = new TextEncoder();
export const b64url = (bytes: Uint8Array) => encodeBase64urlNoPadding(bytes);
export const fromB64url = (s: string) => decodeBase64urlIgnorePadding(s);
export const hex = (bytes: Uint8Array) => encodeHexLowerCase(bytes);
/** Base32 without padding, as authenticator apps expect for a manually typed TOTP secret. */
export const base32 = (bytes: Uint8Array) => encodeBase32NoPadding(bytes);

export const randomBytes = (n: number) => crypto.getRandomValues(new Uint8Array(n));

/** Web Crypto wants bytes backed by a plain ArrayBuffer; this copies when needed (inputs are small). */
const own = (b: Uint8Array): Uint8Array<ArrayBuffer> => new Uint8Array(b);

export const concat = (...parts: Uint8Array[]) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
};

/** Constant-time equality for byte strings of possibly different lengths. */
export const timingSafeEqual = (a: Uint8Array, b: Uint8Array) =>
  a.length === b.length && constantTimeEqual(a, b);

/** Secrets are base64 (as generated by the runbook's `randomBytes(32).toString('base64')`). */
const keyBytes = (secret: string) => {
  const raw = Uint8Array.from(atob(secret), (c) => c.charCodeAt(0));
  if (raw.length < 32) throw new Error("Secret keys must be at least 32 bytes");
  return raw;
};

// One imported key per secret per isolate: importKey is the costly part of an HMAC.
const hmacKeys = new Map<string, Promise<CryptoKey>>();
const hmacKey = (secret: string) => {
  let key = hmacKeys.get(secret);
  if (!key) {
    key = crypto.subtle.importKey("raw", keyBytes(secret), { name: "HMAC", hash: "SHA-256" }, false, [
      "sign",
    ]);
    hmacKeys.set(secret, key);
  }
  return key;
};

export async function hmacSha256(secret: string, data: Uint8Array): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.sign("HMAC", await hmacKey(secret), own(data)));
}

export async function sha256(data: Uint8Array): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.digest("SHA-256", own(data)));
}

const aesKeys = new Map<string, Promise<CryptoKey>>();
const aesKey = (secret: string) => {
  let key = aesKeys.get(secret);
  if (!key) {
    key = crypto.subtle.importKey("raw", keyBytes(secret).slice(0, 32), "AES-GCM", false, [
      "encrypt",
      "decrypt",
    ]);
    aesKeys.set(secret, key);
  }
  return key;
};

/** AES-256-GCM; output = base64url(iv ‖ ciphertext ‖ tag). `aad` binds the ciphertext to its owner. */
export async function encrypt(secret: string, plain: Uint8Array, aad: string): Promise<string> {
  const iv = randomBytes(12);
  const ct = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv, additionalData: enc.encode(aad) },
    await aesKey(secret),
    own(plain),
  );
  return b64url(concat(iv, new Uint8Array(ct)));
}

export async function decrypt(secret: string, sealed: string, aad: string): Promise<Uint8Array> {
  const raw = fromB64url(sealed);
  const pt = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: raw.slice(0, 12), additionalData: enc.encode(aad) },
    await aesKey(secret),
    raw.slice(12),
  );
  return new Uint8Array(pt);
}
