-- Hand-written: integrity triggers (docs/05 §5.3), generated by scripts/write-triggers.ts from src/triggers.ts.
CREATE TRIGGER `documents_frozen_update` BEFORE UPDATE ON `documents` WHEN OLD.frozen_at IS NOT NULL AND (
  NEW.`id` IS NOT OLD.`id`
  OR NEW.`type` IS NOT OLD.`type`
  OR NEW.`client_id` IS NOT OLD.`client_id`
  OR NEW.`project_id` IS NOT OLD.`project_id`
  OR NEW.`care_plan_id` IS NOT OLD.`care_plan_id`
  OR NEW.`parent_id` IS NOT OLD.`parent_id`
  OR NEW.`version_group_id` IS NOT OLD.`version_group_id`
  OR NEW.`version` IS NOT OLD.`version`
  OR NEW.`series` IS NOT OLD.`series`
  OR NEW.`fy` IS NOT OLD.`fy`
  OR NEW.`number` IS NOT OLD.`number`
  OR NEW.`number_display` IS NOT OLD.`number_display`
  OR NEW.`currency` IS NOT OLD.`currency`
  OR NEW.`issue_date` IS NOT OLD.`issue_date`
  OR NEW.`due_date` IS NOT OLD.`due_date`
  OR NEW.`valid_until` IS NOT OLD.`valid_until`
  OR NEW.`supply_type` IS NOT OLD.`supply_type`
  OR NEW.`place_of_supply_code` IS NOT OLD.`place_of_supply_code`
  OR NEW.`recipient` IS NOT OLD.`recipient`
  OR NEW.`fx_rate_micros` IS NOT OLD.`fx_rate_micros`
  OR NEW.`fx_date` IS NOT OLD.`fx_date`
  OR NEW.`fx_source` IS NOT OLD.`fx_source`
  OR NEW.`subtotal_minor` IS NOT OLD.`subtotal_minor`
  OR NEW.`discount_minor` IS NOT OLD.`discount_minor`
  OR NEW.`taxable_minor` IS NOT OLD.`taxable_minor`
  OR NEW.`cgst_minor` IS NOT OLD.`cgst_minor`
  OR NEW.`sgst_minor` IS NOT OLD.`sgst_minor`
  OR NEW.`igst_minor` IS NOT OLD.`igst_minor`
  OR NEW.`round_off_minor` IS NOT OLD.`round_off_minor`
  OR NEW.`total_minor` IS NOT OLD.`total_minor`
  OR NEW.`total_inr_minor` IS NOT OLD.`total_inr_minor`
  OR NEW.`terms_version_id` IS NOT OLD.`terms_version_id`
  OR NEW.`snapshot_sha256` IS NOT OLD.`snapshot_sha256`
  OR NEW.`frozen_at` IS NOT OLD.`frozen_at`
  OR NEW.`issued_by` IS NOT OLD.`issued_by`
  OR NEW.`realisation_due_at` IS NOT OLD.`realisation_due_at`
  OR NEW.`created_by` IS NOT OLD.`created_by`
  OR NEW.`created_at` IS NOT OLD.`created_at`
  OR (OLD.`snapshot_r2_key` IS NOT NULL AND NEW.`snapshot_r2_key` IS NOT OLD.`snapshot_r2_key`)
  OR (OLD.`pdf_r2_key` IS NOT NULL AND NEW.`pdf_r2_key` IS NOT OLD.`pdf_r2_key`)
  OR (OLD.`pdf_sha256` IS NOT NULL AND NEW.`pdf_sha256` IS NOT OLD.`pdf_sha256`)
  OR (OLD.`voided_at` IS NOT NULL AND NEW.`voided_at` IS NOT OLD.`voided_at`)
  OR (OLD.`void_reason` IS NOT NULL AND NEW.`void_reason` IS NOT OLD.`void_reason`)
) BEGIN SELECT RAISE(ABORT, 'issued document is frozen'); END;
--> statement-breakpoint
CREATE TRIGGER `documents_frozen_delete` BEFORE DELETE ON `documents` WHEN OLD.frozen_at IS NOT NULL BEGIN SELECT RAISE(ABORT, 'issued document cannot be deleted'); END;
--> statement-breakpoint
CREATE TRIGGER `document_lines_frozen_insert` BEFORE INSERT ON `document_lines` WHEN (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_lines of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `document_lines_frozen_update` BEFORE UPDATE ON `document_lines` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL OR (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_lines of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `document_lines_frozen_delete` BEFORE DELETE ON `document_lines` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_lines of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `document_sections_frozen_insert` BEFORE INSERT ON `document_sections` WHEN (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_sections of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `document_sections_frozen_update` BEFORE UPDATE ON `document_sections` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL OR (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_sections of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `document_sections_frozen_delete` BEFORE DELETE ON `document_sections` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'document_sections of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `payment_schedules_frozen_insert` BEFORE INSERT ON `payment_schedules` WHEN (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'payment_schedules of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `payment_schedules_frozen_update` BEFORE UPDATE ON `payment_schedules` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL OR (SELECT frozen_at FROM documents WHERE id = NEW.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'payment_schedules of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `payment_schedules_frozen_delete` BEFORE DELETE ON `payment_schedules` WHEN (SELECT frozen_at FROM documents WHERE id = OLD.document_id) IS NOT NULL BEGIN SELECT RAISE(ABORT, 'payment_schedules of an issued document cannot change'); END;
--> statement-breakpoint
CREATE TRIGGER `audit_log_no_update` BEFORE UPDATE ON `audit_log` BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `audit_log_no_delete` BEFORE DELETE ON `audit_log` BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `acceptances_no_update` BEFORE UPDATE ON `acceptances` BEGIN SELECT RAISE(ABORT, 'acceptances is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `acceptances_no_delete` BEFORE DELETE ON `acceptances` BEGIN SELECT RAISE(ABORT, 'acceptances is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `catalogue_price_history_no_update` BEFORE UPDATE ON `catalogue_price_history` BEGIN SELECT RAISE(ABORT, 'catalogue_price_history is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `catalogue_price_history_no_delete` BEFORE DELETE ON `catalogue_price_history` BEGIN SELECT RAISE(ABORT, 'catalogue_price_history is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER `doc_counters_no_decrease` BEFORE UPDATE ON `doc_counters` WHEN NEW.next_no < OLD.next_no OR NEW.series IS NOT OLD.series OR NEW.fy IS NOT OLD.fy BEGIN SELECT RAISE(ABORT, 'document counters only move forward'); END;
--> statement-breakpoint
CREATE TRIGGER `doc_counters_no_delete` BEFORE DELETE ON `doc_counters` BEGIN SELECT RAISE(ABORT, 'document counters cannot be deleted'); END;
--> statement-breakpoint
CREATE VIEW `issue_guard` AS SELECT NULL AS document_id;
--> statement-breakpoint
CREATE TRIGGER `issue_guard_check` INSTEAD OF INSERT ON `issue_guard` WHEN NOT EXISTS (SELECT 1 FROM documents WHERE id = NEW.document_id AND status IN ('draft', 'pending_approval') AND frozen_at IS NULL) BEGIN SELECT RAISE(ABORT, 'document is not an issuable draft'); END;
