// Draws brand/source/techaust-master.svg from geometry.ts (scripts/draw-master.ts writes it; a test checks drift).
import { createRequire } from "node:module";
import { join } from "node:path";
import { LOCKUP, MARK, WORDMARK } from "./geometry.ts";
import { outlineText, pathBounds, transformPath } from "./outline.ts";

/** The wordmark with its bespoke edits applied (see geometry.ts). Returns one path per glyph. */
export async function drawWordmark(packageRoot: string): Promise<string[]> {
  const require = createRequire(join(packageRoot, "package.json"));
  const glyphs = await outlineText(require.resolve(WORDMARK.font), WORDMARK.text, WORDMARK);
  const [t, ...rest] = glyphs;
  if (!t) throw new Error("no T");
  // 45° cut on the T bar: move the bar's lower-right corner left by the bar height.
  const pts = [...t.matchAll(/(-?[\d.]+) (-?[\d.]+)/g)].map((m) => [Number(m[1]), Number(m[2])] as const);
  const maxX = Math.max(...pts.map((p) => p[0]));
  const bar = Math.min(...pts.filter(([, y]) => y > 0.5 && y < WORDMARK.cap - 1).map(([, y]) => y));
  const corner = `L${maxX} ${bar}`;
  if (!t.includes(corner)) throw new Error("T bar corner not found; the font outline changed");
  const cutT = t.replace(corner, `L${Math.round((maxX - bar) * 100) / 100} ${bar}`);
  return [cutT, ...rest.map((g) => transformPath(g, 1, 1, -WORDMARK.kernAfterT, 0))];
}

export async function renderMaster(packageRoot: string): Promise<string> {
  const glyphs = await drawWordmark(packageRoot);
  const box = pathBounds(glyphs.join(""));
  const wx = 100 * LOCKUP.markScale + LOCKUP.gap;
  const width = Math.round((wx + box.x1) * 100) / 100;
  const names = [...WORDMARK.text];
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${LOCKUP.markY} ${width} ${100 * LOCKUP.markScale}">`,
    "  <title>TecHaust Technologies</title>",
    "  <!-- TecHaust logo master, generated by `pnpm --filter @techaust/ui draw:master` from src/brand/geometry.ts. Do not edit. -->",
    `  <g id="mark" transform="translate(0 ${LOCKUP.markY}) scale(${LOCKUP.markScale})">`,
    `    <path id="mark-base" fill="#14231F" d="${MARK.base}"/>`,
    `    <path id="mark-accent" fill="#1E6B5C" d="${MARK.accent}"/>`,
    "  </g>",
    `  <g id="wordmark" fill="#14231F" transform="translate(${wx} 0)">`,
    ...glyphs.map((d, i) => `    <path id="glyph-${i + 1}-${names[i]}" d="${d}"/>`),
    "  </g>",
    "</svg>",
    "",
  ].join("\n");
}
