// Font metrics → @font-face CSS (pure; font parsing via fontkitten, which is pure JS).
import { create } from "fontkitten";
import { FACES, type Face, fontFileName, LETTER_WEIGHTS, unicodeRange } from "./config.ts";

export type Metrics = {
  unitsPerEm: number;
  ascent: number;
  descent: number;
  lineGap: number;
  avgWidth: number;
};

/** fonts/metrics.json: web-font metrics per fallback face (measured at its instance) + system-font metrics. */
export type MetricsFile = {
  web: Record<string, Metrics>;
  system: Record<string, Metrics & { source: string }>;
};

type FontLike = {
  unitsPerEm: number;
  ascent: number;
  descent: number;
  lineGap: number;
  glyphForCodePoint(cp: number): { advanceWidth: number };
  hasGlyphForCodePoint(cp: number): boolean;
};

export const parseFont = (buf: Uint8Array) => create(Buffer.from(buf)) as unknown as FontLike;

export function measure(font: FontLike): Metrics {
  let total = 0;
  let weight = 0;
  for (const [ch, w] of Object.entries(LETTER_WEIGHTS)) {
    const cp = ch.codePointAt(0) ?? 0;
    if (!font.hasGlyphForCodePoint(cp)) throw new Error(`font lacks U+${cp.toString(16)}`);
    total += font.glyphForCodePoint(cp).advanceWidth * w;
    weight += w;
  }
  return {
    unitsPerEm: font.unitsPerEm,
    ascent: font.ascent,
    descent: font.descent,
    lineGap: font.lineGap,
    avgWidth: Math.round((total / weight) * 100) / 100,
  };
}

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;

/** Metric-matched fallback face so the swap from system font to web font barely moves text (CLS). */
export function fallbackFace(family: string, local: string, web: Metrics, sys: Metrics): string {
  const sizeAdjust = web.avgWidth / web.unitsPerEm / (sys.avgWidth / sys.unitsPerEm);
  return [
    "@font-face {",
    `  font-family: "${family}";`,
    `  src: local("${local}");`,
    `  size-adjust: ${pct(sizeAdjust)};`,
    `  ascent-override: ${pct(web.ascent / web.unitsPerEm / sizeAdjust)};`,
    `  descent-override: ${pct(Math.abs(web.descent) / web.unitsPerEm / sizeAdjust)};`,
    `  line-gap-override: ${pct(web.lineGap / web.unitsPerEm / sizeAdjust)};`,
    "}",
  ].join("\n");
}

function webFaces(face: Face): string[] {
  return face.files.map((file) =>
    [
      "@font-face {",
      `  font-family: "${face.family}";`,
      "  font-style: normal;",
      `  font-weight: ${face.weight};`,
      ...(face.stretch ? [`  font-stretch: ${face.stretch};`] : []),
      `  font-display: ${face.display};`,
      `  src: url("../fonts/${fontFileName(face, file)}") format("woff2");`,
      `  unicode-range: ${unicodeRange(file.ranges)};`,
      "}",
    ].join("\n"),
  );
}

/** generated/fonts.css from fonts/metrics.json (pure, so the drift test can regenerate it). */
export function renderFontsCss(metrics: MetricsFile): string {
  const parts = [
    "/* Self-hosted fonts (SIL OFL 1.1, see fonts/LICENSES.md). Generated by `pnpm --filter @techaust/ui build:fonts`. Do not edit. */",
  ];
  for (const face of FACES) {
    parts.push(...webFaces(face));
    for (const fb of face.fallbacks ?? []) {
      const web = metrics.web[fb.family];
      const sys = metrics.system[fb.local];
      if (!web || !sys) throw new Error(`fonts/metrics.json lacks ${fb.family} / ${fb.local}`);
      parts.push(fallbackFace(fb.family, fb.local, web, sys));
    }
  }
  return `${parts.join("\n\n")}\n`;
}
