import { env } from "cloudflare:workers";
import { SETTINGS_DEFAULTS } from "@techaust/core";
import { eq } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { createDb } from "../src/client.ts";
import { catalogueItems, settings } from "../src/schema/index.ts";
import { CATALOGUE } from "../src/seed/catalogue.ts";
import { literal, seedSql, seedStatements } from "../src/seed/index.ts";
import { all, first, run } from "./helpers.ts";

const seed = () => env.DB.batch(seedStatements().map((s) => env.DB.prepare(s)));

describe("seed [ADM-CAT-01]", () => {
  it("loads the catalogue S1–S18 and the settings defaults", async () => {
    await seed();
    const items = await all<{ code: string }>("SELECT code FROM catalogue_items ORDER BY rowid");
    expect(items.map((i) => i.code)).toEqual(Array.from({ length: 18 }, (_, i) => `S${i + 1}`));
    const keys = await all<{ key: string }>("SELECT key FROM settings ORDER BY key");
    expect(keys.map((k) => k.key)).toEqual([
      "company",
      "flags",
      "numbering",
      "payment_terms",
      "retention",
      "tax",
    ]);
  });

  it("is idempotent: running it again changes nothing", async () => {
    await seed();
    const snapshot = async () => ({
      items: await all("SELECT * FROM catalogue_items ORDER BY code"),
      settings: await all("SELECT * FROM settings ORDER BY key"),
    });
    const once = await snapshot();
    await seed();
    await seed();
    expect(await snapshot()).toEqual(once);
  });

  it("never overwrites the Owner's edits", async () => {
    await seed();
    await run("UPDATE catalogue_items SET price_inr_minor = 4500000 WHERE code = 'S1'");
    await run(
      "UPDATE settings SET value = json_set(value, '$.defaultRateBp', 1200), version = 2 WHERE key = 'tax'",
    );
    await seed();
    expect(await first("SELECT price_inr_minor FROM catalogue_items WHERE code = 'S1'")).toEqual({
      price_inr_minor: 4_500_000,
    });
    expect(
      await first(
        "SELECT json_extract(value, '$.defaultRateBp') AS r, version FROM settings WHERE key = 'tax'",
      ),
    ).toEqual({
      r: 1200,
      version: 2,
    });
  });

  it("reads back through Drizzle with typed JSON", async () => {
    await seed();
    const db = createDb(env.DB);
    const [s16] = await db.select().from(catalogueItems).where(eq(catalogueItems.code, "S16"));
    expect(s16?.defaultLines?.map((l) => l.description)).toEqual(["Essential", "Growth", "Scale"]);
    expect(s16?.schedule).toEqual([{ label: "Monthly in advance", pctBp: 10_000, trigger: "monthly" }]);
    expect(s16?.active).toBe(true);
    // (Tests in one file share a database; "tax" was edited above, so read an untouched key.)
    const [numbering] = await db.select().from(settings).where(eq(settings.key, "numbering"));
    expect(numbering?.value).toEqual(SETTINGS_DEFAULTS.numbering);
  });

  it("matches the approved catalogue (docs/02 §4.1, Q-P3-6, docs/08 G-2)", () => {
    const byCode = Object.fromEntries(CATALOGUE.map((c) => [c.code, c]));
    expect(byCode.S1).toMatchObject({ priceInr: 40_000_00, priceUsd: 2_000_00, slug: "discovery-sprint" });
    expect(byCode.S5).toMatchObject({ priceInr: 3_00_000_00, priceUsd: 12_000_00 });
    expect(byCode.S18).toMatchObject({ priceInr: 1_75_000_00, priceUsd: 2_900_00 });
    expect(byCode.S3).toMatchObject({ priceUsd: null, showOnSite: false });
    for (const item of CATALOGUE) {
      expect(
        item.schedule.reduce((a, s) => a + s.pctBp, 0),
        item.code,
      ).toBe(10_000);
      expect(item.sac, item.code).toMatch(/^99831[3-6]$/);
      // Q-P3-6: jobs under ₹1 L are 100 % upfront; monthly services are billed monthly in advance.
      const expected =
        item.unit === "month"
          ? "monthly"
          : (item.priceInr ?? 0) < SETTINGS_DEFAULTS.payment_terms.smallJobThreshold.INR
            ? "upfront"
            : "build";
      const actual =
        item.schedule[0]?.trigger === "monthly"
          ? "monthly"
          : item.schedule.length === 1
            ? "upfront"
            : "build";
      expect(actual, item.code).toBe(expected);
    }
  });

  it("produces SQL for wrangler d1 execute, with safe literals", () => {
    expect(seedSql()).toMatch(/^-- Generated by .*\nINSERT INTO `settings`/);
    expect(literal("it's")).toBe("'it''s'");
    expect(literal(null)).toBe("NULL");
    expect(literal(true)).toBe("1");
    expect(literal({ a: "b'c" })).toBe(`'{"a":"b''c"}'`);
    expect(() => literal(1.5)).toThrow(RangeError);
  });
});
